### PR TITLE
Remove interrupt support (no interrupt on chip or breakout)

### PR DESCRIPTION
**Pull request by anecdata**
Remove mentions and register settings for interrupts. The chip only has power, ground, SDA, and SCL. No interrupt pin on breakout either.

The [datasheet](https://www.vishay.com/docs/84286/veml7700.pdf) notes on p.7:
> Interrupt pin not available for VEML7700

The docs were confusing for including (unsupported) interrupt features.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Thank you!

**Comment by RaNo99** [comment]
I don't think you made the right thing by removing the interrupts notion. They **are** usable even if there is no dedicated pin. The chip has a feature of setting the interrupt bits (in the ALS_INT register) with persistence protection (ALS_PERS) which you can read instead of the ALS register. This is helpful for continuous ambient light tracking with smoothing done by VEML7700 instead of your custom logic that would require more I2C communication.

**Comment by RaNo99** [comment]
Hi, yes, I tried the old version and it indeed worked. Then I had to resort to a non-interrupt solution because I needed more flexibility, so I don't have the code example anymore.

**Comment by ladyada** [comment]
yes please revert - better to add documentation to the readme explaining there's no external IRQ

**Pull request merged**
